package app.podor.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import app.podor.domain.Language

val LocalLanguage = staticCompositionLocalOf { Language.Chinese }

@Composable fun tr(value: String): String = trValue(value, LocalLanguage.current)

fun trValue(value: String, language: Language): String {
    if (language == Language.Chinese) return value
    english[value]?.let {
        return it
    }
    val divider = value.indexOf(" · ")
    if (divider > 0)
        return trValue(value.substring(0, divider), language) + value.substring(divider)
    if (value.startsWith("图层 ")) return "Layer " + value.removePrefix("图层 ")
    if (value.startsWith("颜色 #")) return "Color #" + value.removePrefix("颜色 #")
    if (value.startsWith("隐藏 ")) return "Hide " + value.removePrefix("隐藏 ")
    if (value.startsWith("显示 ")) return "Show " + value.removePrefix("显示 ")
    return value
}

private val english =
    mapOf(
        "关于与更新" to "About & updates",
        "稳定版" to "Stable",
        "软件更新" to "Software update",
        "正在检查更新" to "Checking for updates",
        "已是最新版本" to "You're up to date",
        "发现新版本" to "Update available",
        "正在下载" to "Downloading",
        "安装包已就绪" to "Ready to install",
        "暂时无法更新" to "Update unavailable",
        "保存作品并退出应用，再打开安装包完成更新。" to "Save your work and quit the app before opening the installer.",
        "打开下载文件夹" to "Show download folder",
        "下载更新" to "Download update",
        "重新检查" to "Check again",
        "重试" to "Retry",
        "检查更新" to "Check for updates",
        "更新内容" to "What's new",
        "连接失败，请稍后重试" to "Could not connect. Please try again.",
        "更新信息无效" to "Invalid update information",
        "安装包校验失败，请重新下载" to "Verification failed. Download again.",
        "无法保存安装包，请检查磁盘空间" to "Could not save the installer. Check available disk space.",
        "更新通道尚未配置" to "Update channel is not configured",
        "工作台" to "Studio",
        "导出图像" to "Export image",
        "导出" to "Export",
        "透明背景" to "Transparent background",
        "JPEG 使用白色背景" to "JPEG uses a white background",
        "图像质量" to "Image quality",
        "高兼容" to "Compatible",
        "无损" to "Lossless",
        "JPEG 已导出" to "JPEG exported",
        "WebP 已导出" to "WebP exported",
        "缩略图生成失败" to "Could not generate thumbnails",
        "跳过启动动画" to "Skip intro",
        "画笔" to "Brush",
        "笔刷库" to "Brush library",
        "橡皮" to "Eraser",
        "矩形选区" to "Marquee",
        "填充" to "Fill",
        "取色" to "Eyedropper",
        "移动" to "Pan",
        "移动画布" to "Pan canvas",
        "颜色" to "Color",
        "调色盘" to "Color wheel",
        "图层" to "Layers",
        "混合模式" to "Blend mode",
        "正常" to "Normal",
        "正片叠底" to "Multiply",
        "滤色" to "Screen",
        "叠加" to "Overlay",
        "柔光" to "Soft light",
        "变暗" to "Darken",
        "变亮" to "Lighten",
        "差值" to "Difference",
        "调整" to "Adjust",
        "设置" to "Settings",
        "语言" to "Language",
        "快捷键" to "Shortcuts",
        "插件" to "Plugins",
        "关闭" to "Close",
        "编辑笔刷" to "Brush editor",
        "大小" to "Size",
        "不透明度" to "Opacity",
        "墨水笔" to "Ink",
        "勾线笔" to "Liner",
        "稳笔" to "Stabilization",
        "马克笔" to "Marker",
        "柔边笔" to "Soft",
        "铅笔" to "Pencil",
        "炭笔" to "Charcoal",
        "喷枪" to "Airbrush",
        "水彩" to "Watercolor",
        "斜头笔" to "Chisel",
        "平刷" to "Flat",
        "点描" to "Stipple",
        "手指绘画" to "Finger drawing",
        "名称" to "Name",
        "圆形" to "Round",
        "扁平" to "Flat",
        "硬度" to "Hardness",
        "笔尖比例" to "Aspect",
        "角度" to "Angle",
        "颗粒" to "Grain",
        "间距" to "Spacing",
        "保存为新笔刷" to "Save as new brush",
        "完成" to "Done",
        "取消" to "Cancel",
        "按下快捷键" to "Press a shortcut",
        "恢复默认" to "Reset defaults",
        "仅支持字母、数字和组合键" to "Use a letter or digit with optional modifiers",
        "快捷键已被占用" to "Shortcut already in use",
        "导入笔刷包" to "Import brush pack",
        "导出笔刷包" to "Export brush pack",
        "导入 JSON 笔刷扩展包" to "Import a JSON brush pack",
        "移除插件" to "Remove plugin",
        "自定义笔刷" to "Custom brushes",
        "删除笔刷" to "Delete brush",
        "自由创作" to "Untitled",
        "工程菜单" to "Project",
        "新建画布" to "New canvas",
        "打开工程 / 图片" to "Open project / image",
        "保存工程" to "Save project",
        "清空当前图层" to "Clear layer",
        "快捷键与手势" to "Shortcuts & gestures",
        "取消选区" to "Deselect",
        "撤销" to "Undo",
        "重做" to "Redo",
        "导出" to "Export",
        "适合窗口" to "Fit canvas",
        "更多工具" to "More tools",
        "图层与工作台" to "Layers & studio",
        "画笔、颜色与图层" to "Studio",
        "关闭工作台" to "Close studio",
        "选择颜色" to "Color picker",
        "饱和度与明度色板" to "Saturation and brightness",
        "色相" to "Hue",
        "HEX 颜色" to "HEX color",
        "工作室色卡" to "Studio palette",
        "饱和度" to "Saturation",
        "明度" to "Value",
        "亮度" to "Brightness",
        "对比度" to "Contrast",
        "新建图层" to "Add layer",
        "图层不透明度" to "Layer opacity",
        "重命名" to "Rename",
        "上移图层" to "Move up",
        "下移图层" to "Move down",
        "删除图层" to "Delete layer",
        "重命名图层" to "Rename layer",
        "保存" to "Save",
        "明暗与色彩" to "Tone & color",
        "仅作用于当前图层的选区" to "Active layer selection",
        "作用于当前图层" to "Active layer",
        "应用色彩调整" to "Apply tone",
        "高斯模糊" to "Gaussian blur",
        "半径" to "Radius",
        "应用模糊" to "Apply blur",
        "填充设置" to "Fill",
        "颜色容差" to "Tolerance",
        "点击应用后生效，可随时撤销。" to "Apply, then undo at any time.",
        "选择填充工具，轻点连通区域。颜色与不透明度沿用画笔设置。" to "Tap a connected area. Uses brush color and opacity.",
        "请先保存当前工程，新画布会替换当前内容。" to "Save your work before replacing the canvas.",
        "打开工程或图片" to "Open project or image",
        "打开后会替换当前画布，重要改动请先保存。" to "Save your work before opening another canvas.",
        "选择文件" to "Choose file",
        "清空当前图层？" to "Clear this layer?",
        "清空后仍可撤销。" to "You can undo this action.",
        "清空" to "Clear",
        "暂时无法完成" to "Unable to complete",
        "知道了" to "OK",
        "宽度" to "Width",
        "高度" to "Height",
        "创建" to "Create",
        "自定义尺寸" to "Custom size",
        "尺寸超出限制" to "Size exceeds limits",
        "横向画布" to "Landscape",
        "方形画布" to "Square",
        "竖向画布" to "Portrait",
        "高清画布" to "HD",
        "交换宽高" to "Swap dimensions",
        "准备画布…" to "Preparing canvas…",
        "画布已就绪" to "Canvas ready",
        "工程已打开" to "Project opened",
        "PNG 已导出" to "PNG exported",
        "工程已保存" to "Project saved",
        "已自动保存到本机" to "Saved on this device",
        "笔刷包已导入" to "Brush pack imported",
        "笔刷包过大" to "Brush pack is too large",
        "笔刷包参数无效" to "Invalid brush pack",
        "设置参数无效" to "Invalid settings",
        "插件数量超过限制" to "Plugin limit reached",
        "设置文件无法读取，已使用默认设置" to "Could not read settings; defaults loaded",
        "填充位置不在选区内" to "Fill position is outside the selection",
        "请先显示当前图层" to "Show the active layer first",
        "已达到图层上限" to "Layer limit reached",
        "至少保留一个图层" to "Keep at least one layer",
        "画布尺寸超出限制" to "Canvas size exceeds limits",
        "不是有效的podor工程" to "Not a valid podor project",
        "文件过大" to "File is too large",
        "请选择 podor 工程或 PNG、JPEG、WebP 图片" to
            "Choose a podor project or a PNG, JPEG or WebP image",
        "图片数据损坏或格式不受支持" to "Image is damaged or its format is unsupported",
        "暂不支持动态 WebP，请先导出为静态图片" to "Animated WebP is not supported; export a still image first",
        "图片解码超过内存限制" to "Image decoding exceeds the memory limit",
        "无法读取图片方向" to "Could not read image orientation",
        "工程文件已损坏" to "Project file is damaged",
        "导入的图像" to "Imported image",
    )
