package app.podor.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import app.podor.domain.Language

val LocalLanguage = staticCompositionLocalOf { Language.Chinese }

@Composable fun tr(value: String): String = trValue(value, LocalLanguage.current)

fun trValue(value: String, language: Language): String {
    if (language == Language.Chinese) return value
    english[value]?.let {
        return it
    }
    val divider = value.indexOf(" · ")
    if (divider > 0)
        return trValue(value.substring(0, divider), language) + value.substring(divider)
    if (value.startsWith("图层 ")) return "Layer " + value.removePrefix("图层 ")
    if (value.startsWith("蒙版 ")) return "Mask " + value.removePrefix("蒙版 ")
    if (value.startsWith("颜色 #")) return "Color #" + value.removePrefix("颜色 #")
    if (value.startsWith("隐藏 ")) return "Hide " + value.removePrefix("隐藏 ")
    if (value.startsWith("显示 ")) return "Show " + value.removePrefix("显示 ")
    if (value.startsWith("Aseprite 区块 0x") && value.endsWith(" 暂不支持，工程未导入"))
        return "Aseprite chunk " +
            value.removePrefix("Aseprite 区块 ").substringBefore(' ') +
            " is unsupported. The project was not imported."
    if (value.startsWith("Aseprite 导出不支持："))
        return "This project contains features that Aseprite export cannot preserve yet."
    if (value.startsWith("Aseprite 可编辑导出无法保留："))
        return "Choose a composited frame copy to export these project features."
    return value
}

private val english =
    mapOf(
        "导出 Aseprite 工程副本" to "Export Aseprite project copy",
        "Aseprite 工程副本" to "Aseprite project copy",
        "导出合成帧副本" to "Export composited frame copy",
        "这些工程数据暂时无法保留。" to "These project features cannot be preserved yet.",
        "以下内容需要逐帧合成。" to "These features require compositing each frame.",
        "保留全部帧、时长和播放范围。副本中每帧合并为一层，原工程不变。" to
            "Keeps every frame, duration and playback range. Each frame in the copy is merged into one layer. Your project stays unchanged.",
        "混合图层组模式" to "Mixed group modes",
        "透明度锁定" to "Alpha lock",
        "图层不透明度精度" to "Layer opacity precision",
        "绘画辅助线" to "Drawing guides",
        "色板排列" to "Palette order",
        "附加工程色板" to "Companion project palette",
        "Aseprite 工程元数据无效或超出限制" to "The Aseprite project metadata is invalid or exceeds the limit.",
        "Aseprite 网格尺寸超出限制" to "The Aseprite grid exceeds the size limit.",
        "Aseprite 导出请求已过期" to "The project changed. Export the Aseprite copy again.",
        "请先结束笔画再导出 Aseprite 工程" to
            "Finish the current stroke before exporting the Aseprite project.",
        "Aseprite 混合模式暂不支持" to "This Aseprite blend mode is unsupported.",
        "Aseprite 数据长度无效" to "The Aseprite data length is invalid.",
        "Aseprite 数据被截断" to "The Aseprite file is incomplete.",
        "Aseprite 名称超出长度限制" to "An Aseprite name exceeds the length limit.",
        "Aseprite 名称不是有效 UTF-8" to "An Aseprite name is not valid UTF-8.",
        "Aseprite 数据包含未支持的附加字段" to "The Aseprite file contains unsupported extra fields.",
        "Aseprite 色板数量超出限制" to "The Aseprite palette exceeds the color limit.",
        "Aseprite 色板范围无效" to "The Aseprite palette range is invalid.",
        "Aseprite 色板属性暂不支持" to "These Aseprite palette properties are unsupported.",
        "Aseprite 六位色板无效" to "The Aseprite 6-bit palette is invalid.",
        "Aseprite 图层类型或属性暂不支持" to "This Aseprite layer type or property is unsupported.",
        "Aseprite 图层层级无效" to "The Aseprite layer hierarchy is invalid.",
        "Aseprite 像素图层折叠属性无效" to "An Aseprite image layer has an invalid collapsed flag.",
        "Aseprite 标签数量超出限制" to "The Aseprite playback range count exceeds the limit.",
        "Aseprite 标签方向无效" to "An Aseprite playback direction is invalid.",
        "Aseprite 标签范围或往返重复语义暂不支持" to
            "The Aseprite playback range is invalid or uses unsupported ping-pong repeat semantics.",
        "Aseprite 解码大小无效" to "The Aseprite decoded size is invalid.",
        "Aseprite 解码像素超过限制" to "The Aseprite decoded pixels exceed the limit.",
        "Aseprite 像素索引超出色板" to "An Aseprite pixel index is outside its palette.",
        "Aseprite 工程内存超出限制" to "The Aseprite project exceeds the memory limit.",
        "Aseprite zlib 像素无效" to "The compressed Aseprite pixels are invalid.",
        "Aseprite zlib 解码大小超出声明" to
            "The compressed Aseprite data expands beyond its declared size.",
        "Aseprite zlib 长度或尾随数据无效" to
            "The compressed Aseprite data has an invalid length or trailing bytes.",
        "Aseprite zlib 流被截断" to "The compressed Aseprite data is incomplete.",
        "Aseprite 像素长度无效" to "The Aseprite pixel data length is invalid.",
        "Aseprite 文件大小超出限制" to "The Aseprite file exceeds the size limit.",
        "Aseprite 文件头无效" to "The Aseprite file header is invalid.",
        "Aseprite 帧数、颜色模式或配置暂不支持" to
            "The Aseprite frame count, color mode or configuration is unsupported.",
        "Aseprite 帧长度无效" to "An Aseprite frame length is invalid.",
        "Aseprite 帧标识无效" to "An Aseprite frame header is invalid.",
        "Aseprite 区块数量无效" to "The Aseprite chunk count is invalid.",
        "Aseprite 帧时长无效" to "An Aseprite frame duration is invalid.",
        "Aseprite 区块长度无效" to "An Aseprite chunk length is invalid.",
        "Aseprite 图层布局或数量无效" to "The Aseprite layer layout or count is invalid.",
        "Aseprite 帧图像数量超出限制" to "The Aseprite frame image count exceeds the limit.",
        "Aseprite ICC 或固定伽马配置暂不支持" to "Aseprite ICC profiles and fixed gamma are unsupported.",
        "逐帧 Aseprite 色彩配置暂不支持" to "Per-frame Aseprite color profiles are unsupported.",
        "Aseprite 重复或逐帧标签暂不支持" to "Repeated or per-frame Aseprite playback ranges are unsupported.",
        "Aseprite 非标签用户数据暂不支持" to "Aseprite user data outside playback ranges is unsupported.",
        "Aseprite 标签用户数据数量无效" to "The Aseprite playback range user data count is invalid.",
        "Aseprite 文本或属性用户数据暂不支持" to "Aseprite text and property user data are unsupported.",
        "Aseprite 初始色板数据不完整" to "The initial Aseprite palette is incomplete.",
        "逐帧 Aseprite 色板或名称暂不支持" to "Per-frame Aseprite palettes or color names are unsupported.",
        "Aseprite 索引工程缺少色板" to "The indexed Aseprite project has no palette.",
        "Aseprite 透明色槽无效" to "The Aseprite transparent palette slot is invalid.",
        "Aseprite 图像引用的图层不存在" to "An Aseprite image refers to a missing layer.",
        "Aseprite 图像位置、不透明度或层叠偏移暂不支持" to
            "This Aseprite image placement, opacity or stacking offset is unsupported.",
        "Aseprite 链接图像必须引用之前的帧" to "A linked Aseprite image must refer to an earlier frame.",
        "Aseprite 链接图像不存在" to "The linked Aseprite image is missing.",
        "不同放置位置的链接图像暂不支持" to "Linked Aseprite images with different placements are unsupported.",
        "Aseprite 图像尺寸超出画布" to "An Aseprite image extends outside the canvas.",
        "Aseprite 图像数量超出限制" to "The Aseprite image count exceeds the limit.",
        "Aseprite 图块图像暂不支持" to "Aseprite tilemap images are unsupported.",
        "Aseprite 工程没有图层" to "The Aseprite project has no layers.",
        "Aseprite 导出工作量过大" to "The Aseprite export workload exceeds the limit.",
        "Aseprite 导出像素工作量超过限制" to
            "The Aseprite export is too large. Use fewer frames or a smaller canvas.",
        "Aseprite 导出解码大小过大" to "The Aseprite decoded export size exceeds the limit.",
        "Aseprite 导出累计图像大小超过限制" to "The total Aseprite image size exceeds the limit.",
        "Aseprite 可编辑导出不支持矢量 Cel" to
            "Editable Aseprite export cannot preserve vector frame content.",
        "Aseprite 合成导出工作内存超过限制" to "Composited Aseprite export exceeds the memory limit.",
        "Aseprite 输出失败或超过大小限制" to "Aseprite output failed or exceeds the size limit.",
        "Aseprite 输出位置无效" to "The Aseprite output position is invalid.",
        "Aseprite 名称超过长度限制" to "An Aseprite name exceeds the length limit.",
        "Aseprite 名称过长" to "An Aseprite name is too long.",
        "Aseprite 数据块过大" to "An Aseprite data block exceeds the size limit.",
        "Aseprite 图层深度过大" to "The Aseprite layer hierarchy is too deep.",
        "Aseprite 调色板过大" to "The Aseprite palette exceeds the color limit.",
        "Aseprite 调色板为空" to "The Aseprite palette is empty.",
        "Aseprite 标签缺少动画" to "An Aseprite playback range has no animation.",
        "Aseprite 标签过多" to "The Aseprite playback range count exceeds the limit.",
        "Aseprite 标签帧无效" to "An Aseprite playback range refers to an invalid frame.",
        "Aseprite 合成带过大" to "The Aseprite compositing strip exceeds the size limit.",
        "Aseprite 导出工作内存超过限制" to "The Aseprite export exceeds the memory limit.",
        "Aseprite 图层编号过大" to "The Aseprite layer index exceeds the limit.",
        "Aseprite Cel 位置无效" to "An Aseprite frame image position is invalid.",
        "Aseprite Cel 尺寸无效" to "An Aseprite frame image size is invalid.",
        "Aseprite 图像压缩失败或超过输出限制" to
            "Aseprite image compression failed or exceeds the output limit.",
        "Aseprite 帧过多" to "The Aseprite frame count exceeds the limit.",
        "Aseprite 画布过大" to "The Aseprite canvas exceeds the size limit.",
        "Aseprite 不支持矢量 Cel" to "Aseprite cannot preserve vector frame content.",
        "Aseprite 帧过大" to "An Aseprite frame exceeds the size limit.",
        "Aseprite 文件过大" to "The Aseprite file exceeds the size limit.",
        "有限次数的往返播放" to "Finite ping-pong playback",
        "工程大小限制" to "Project size limit",
        "工程元数据" to "Project metadata",
        "像素精度" to "Pixel precision",
        "暂不支持的工程内容" to "Unsupported project features",
        "工程已改变，请重新导出 Aseprite 副本" to "The project changed. Export the Aseprite copy again.",
        "当前平台不支持 Aseprite 工程导出" to "Aseprite project export is unavailable on this platform.",
        "当前工程包含暂不支持的 Aseprite 播放或工程数据" to
            "This project contains playback or project data that Aseprite export cannot preserve yet.",
        "请明确选择导出合成帧副本" to "Choose a composited frame copy to export these features.",
        "Aseprite 工程副本已导出" to "Aseprite project copy exported",
        "支持 .pod 工程、旧 .podor 工程、Aseprite、PSD、ORA、PNG、JPEG 和 WebP。" to
            "Supports .pod and legacy .podor projects, Aseprite, PSD, ORA, PNG, JPEG and WebP.",
        "导出动画" to "Export animation",
        "PNG 图集" to "PNG atlas",
        "导出范围" to "Export range",
        "全部动画帧" to "All frames",
        "全部帧" to "All frames",
        "动画导出请求已过期" to "The animation changed. Export it again.",
        "请先结束笔画再导出动画" to "Finish the current stroke before exporting.",
        "工程没有动画" to "This project has no animation.",
        "动画标签不存在" to "The playback range is unavailable.",
        "导出范围中的帧不存在" to "A frame in the export range is unavailable.",
        "动画没有帧" to "The animation has no frames.",
        "动画播放序列超出限制" to "The playback sequence exceeds the frame limit.",
        "动画导出总处理像素超出限制，请缩小范围或画布" to
            "The animation is too large. Use fewer frames or a smaller canvas.",
        "GIF 不能精确保留半透明像素，请明确选择底色合成或透明阈值" to
            "GIF cannot preserve partial transparency. Choose a matte color or alpha threshold.",
        "透明阈值必须在 1 到 255 之间" to "The alpha threshold must be between 1 and 255.",
        "GIF 帧时长需为 10 ms 的倍数，请明确选择时长取整" to
            "Exact GIF timing requires multiples of 10 ms. Turn off exact timing to round it.",
        "GIF 导出工作内存超出限制" to "The GIF export exceeds the memory limit.",
        "GIF 精确导出每帧不能超过 256 个颜色，请明确选择颜色量化" to
            "Exact GIF export supports up to 256 colors per frame. Choose color quantization.",
        "图集列数或边距超出限制" to "The atlas columns or padding exceed the limit.",
        "图集尺寸超出限制" to "The atlas exceeds the size limit.",
        "图集尺寸超出限制，请减少帧或缩小画布" to "The atlas is too large. Use fewer frames or a smaller canvas.",
        "图集元数据超出限制" to "The atlas playback data exceeds the size limit.",
        "播放范围已失效" to "Playback range is unavailable",
        "播放方向" to "Playback direction",
        "高级设置" to "Advanced settings",
        "颜色处理" to "Color handling",
        "透明处理" to "Alpha handling",
        "精确保留颜色" to "Exact colors",
        "精确保留透明度" to "Exact alpha",
        "透明阈值" to "Alpha threshold",
        "合成底色" to "Matte color",
        "使用画笔颜色" to "Use brush color",
        "保持精确时长" to "Exact frame timing",
        "图集列数" to "Atlas columns",
        "透明边距" to "Transparent padding",
        "0 为自动排列" to "0 arranges automatically",
        "当前引擎不支持动画导出" to "This engine does not support animation export",
        "动画帧数据无效" to "Invalid animation frame data",
        "播放范围已失效，请重新选择" to "The playback range is unavailable; select it again",
        "动画导出参数无效" to "Invalid animation export settings",
        "导出帧数量超出限制" to "The export exceeds the frame limit",
        "导出画布尺寸超出限制" to "The export exceeds the canvas limit",
        "导出范围过大，请减少帧或缩小画布" to "The export is too large; use fewer frames or a smaller canvas",
        "图集尺寸超出限制，请减少帧或修改列数" to "The atlas is too large; use fewer frames or change its columns",
        "GIF 精确时长需要为 10 ms 的倍数" to "Exact GIF timing requires multiples of 10 ms",
        "ZIP 内含 PNG 图集与播放数据，保留透明度和帧时长。" to
            "The ZIP contains a PNG atlas and playback data, preserving alpha and frame timing.",
        "GIF 颜色量化，透明边缘与时长可能变化。" to
            "GIF colors are quantized; transparent edges and frame timing may change.",
        "GIF 仅支持有限颜色、二值透明和 10 ms 时长精度。" to
            "GIF supports limited colors, binary transparency and 10 ms timing precision.",
        "动画时间轴" to "Animation timeline",
        "新建播放范围" to "New playback range",
        "编辑播放范围" to "Edit playback range",
        "删除播放范围" to "Delete playback range",
        "播放范围名称" to "Range name",
        "起始帧" to "First frame",
        "结束帧" to "Last frame",
        "循环次数" to "Repeat count",
        "0 为无限循环" to "0 repeats forever",
        "关联帧内容" to "Linked frame content",
        "动画帧" to "Frame",
        "上一帧" to "Previous frame",
        "下一帧" to "Next frame",
        "播放动画" to "Play animation",
        "停止动画" to "Stop animation",
        "洋葱皮" to "Onion skin",
        "添加空白帧" to "Add blank frame",
        "复制动画帧" to "Duplicate frame",
        "共享复制帧" to "Duplicate linked frame",
        "删除动画帧" to "Delete frame",
        "动画设置" to "Animation settings",
        "帧时长" to "Frame duration",
        "确认帧时长" to "Apply frame duration",
        "正向播放" to "Forward",
        "反向播放" to "Reverse",
        "往返播放" to "Ping pong",
        "反向往返" to "Reverse ping pong",
        "前移帧" to "Move frame earlier",
        "后移帧" to "Move frame later",
        "解除单元共享" to "Make frame content independent",
        "清除当前帧单元" to "Clear layer in this frame",
        "动画已改变，请重新导出" to "The animation changed. Export it again.",
        "动画已导出" to "Animation exported",
        "收起时间轴" to "Hide timeline",
        "请先停止动画播放或等待帧切换完成" to "Stop playback or wait for the frame change",
        "请先结束当前笔画" to "Finish the current stroke first",
        "笔画所属帧已切换" to "The stroke's frame has changed",
        "笔画所属图层已切换" to "The stroke's layer has changed",
        "动画预览超出缓存上限" to "The animation preview exceeds the cache limit",
        "漫画线条" to "Comic lines",
        "线条类型" to "Line type",
        "集中线" to "Concentration lines",
        "速度线" to "Speed lines",
        "设置线条" to "Line settings",
        "确认线条" to "Generate lines",
        "取消线条" to "Cancel lines",
        "线条数量" to "Line count",
        "线宽" to "Line width",
        "线条不透明度" to "Line opacity",
        "随机变化" to "Random variation",
        "起点收锋" to "Start taper",
        "终点收锋" to "End taper",
        "起始角度" to "Start angle",
        "展开角度" to "Sweep",
        "内圈横向半径" to "Inner radius X",
        "内圈纵向半径" to "Inner radius Y",
        "外圈横向半径" to "Outer radius X",
        "外圈纵向半径" to "Outer radius Y",
        "线条角度" to "Line angle",
        "线条长度" to "Line length",
        "线条间距" to "Line spacing",
        "线条颜色" to "Line color",
        "随机种子" to "Seed",
        "线条参数无效" to "Invalid line settings",
        "请先确认或取消线条生成" to "Generate or cancel the lines first",
        "绘画助手" to "Drawing assistants",
        "添加助手" to "Add assistant",
        "平行线助手" to "Parallel lines",
        "集中线助手" to "Concentration guide",
        "一点透视" to "One-point perspective",
        "两点透视" to "Two-point perspective",
        "三点透视" to "Three-point perspective",
        "吸附助手" to "Snap to assistant",
        "助手可见性" to "Guide visibility",
        "删除助手" to "Delete assistant",
        "选择助手" to "Select assistant",
        "结束编辑" to "Finish assistant editing",
        "确认助手编辑" to "Confirm assistant edit",
        "取消助手编辑" to "Cancel assistant edit",
        "请先确认或取消助手编辑" to "Confirm or cancel the assistant edit first",
        "调整选区" to "Refine selection",
        "全彩色" to "RGBA color",
        "索引色" to "Indexed color",
        "索引色画布" to "Indexed canvas",
        "转换为索引色" to "Convert to indexed color",
        "转换为全彩色" to "Convert to RGBA",
        "工程调色板" to "Document palette",
        "添加调色板颜色" to "Add palette color",
        "向前排列颜色" to "Move color earlier",
        "向后排列颜色" to "Move color later",
        "替换并移除颜色" to "Replace and remove color",
        "替换为" to "Replace with",
        "应用到调色板" to "Apply palette color",
        "颜色透明度" to "Color alpha",
        "调色板量化" to "Quantize to palette",
        "索引色模式暂不支持此工具" to "This tool is not available in indexed mode yet",
        "索引色模式暂不支持此调整" to "This adjustment is not available in indexed mode yet",
        "索引色模式请使用像素画笔" to "Use a pixel brush in indexed mode",
        "索引色选区移动尚未实现" to "Moving selected pixels is not available in indexed mode yet",
        "合成颜色不在调色板中，请选择量化导出或普通 PNG" to
            "The composite contains colors outside the palette; choose quantization or regular PNG",
        "索引调色板数据无效" to "Invalid indexed palette",
        "索引调色板顺序无效" to "Invalid palette order",
        "当前工程不是索引色模式" to "This document is not in indexed mode",
        "请选择索引颜色" to "Select a palette color",
        "请选择有效索引颜色" to "Select a valid palette color",
        "索引颜色不存在" to "The palette color does not exist",
        "调色板删除或替换参数无效" to "Invalid palette replacement",
        "删除颜色会超出撤销内存限制" to "Removing this color would exceed the undo memory limit",
        "转换会超出撤销内存限制" to "Conversion would exceed the undo memory limit",
        "转换后的工程超出像素内存限制" to "Conversion would exceed the pixel memory limit",
        "索引色模式请使用像素笔；软笔和涂抹请先转换为 RGBA" to
            "Use a pixel brush in indexed mode; convert to RGBA for soft brushes or smudging",
        "此操作尚未支持索引色，请先转换为 RGBA" to "Convert to RGBA to use this operation",
        "像素调整尚未支持索引色，请先转换为 RGBA" to "Convert to RGBA to adjust pixels",
        "索引色图层烘焙尚未支持，请先转换为 RGBA" to "Convert to RGBA to bake layers",
        "索引色图层导入尚未支持，请先转换为 RGBA" to "Convert to RGBA to import a layer",
        "索引色复制尚未支持，请先转换为 RGBA" to "Convert to RGBA to copy pixels",
        "索引色粘贴尚未支持，请先转换为 RGBA" to "Convert to RGBA to paste pixels",
        "索引色选区移动尚未支持，请先取消选区或转换为 RGBA" to
            "Clear the selection or convert to RGBA to move indexed pixels",
        "索引色变换请使用最近邻采样" to "Use nearest-neighbor sampling for indexed transforms",
        "索引色缩放请使用最近邻采样" to "Use nearest-neighbor sampling to resize indexed pixels",
        "请先转换为索引色工程" to "Convert the document to indexed mode first",
        "请指定索引调色板" to "Choose an indexed palette",
        "RGBA 转换不接受索引调色板" to "RGBA conversion does not use an indexed palette",
        "图片不是索引色 PNG" to "This PNG is not indexed",
        "暂不支持动画 PNG，请先导出为静态图片" to "Export a still image to open this animated PNG",
        "索引 PNG 位深无效" to "Invalid indexed PNG bit depth",
        "索引 PNG 缺少调色板" to "The indexed PNG has no palette",
        "索引 PNG 调色板无效" to "Invalid indexed PNG palette",
        "索引 PNG 透明度数量超过调色板" to "The PNG has more alpha values than palette entries",
        "PNG 像素索引超出调色板" to "A PNG pixel refers to an invalid palette entry",
        "色板文件" to "Palette files",
        "剪贴到下方图层" to "Clip to layer below",
        "解除剪贴" to "Release clipping mask",
        "图层操作" to "Layer actions",
        "图层组" to "Layer group",
        "新建图层组" to "New group",
        "选择多个图层" to "Select layers",
        "结束选择图层" to "Finish selecting layers",
        "将选中图层分组" to "Group selected",
        "请选择组内图层" to "Select a layer inside the group",
        "请选择同一层级的相邻图层" to "Select adjacent layers in the same group",
        "移出图层组" to "Move out of group",
        "移入图层组" to "Move into",
        "取消图层分组" to "Ungroup",
        "独立合成" to "Isolated",
        "穿透" to "Pass through",
        "展开" to "Expand",
        "收起" to "Collapse",
        "色彩和谐" to "Color harmony",
        "互补色" to "Complementary",
        "分裂互补色" to "Split complementary",
        "邻近色" to "Analogous",
        "三角色" to "Triadic",
        "四角色" to "Tetradic",
        "图层节点超过限制" to "The layer node limit has been reached",
        "图层组嵌套超过限制" to "The group nesting limit has been reached",
        "同级最底层不能使用剪贴蒙版" to "The bottom sibling cannot be a clipping mask",
        "穿透图层组暂不能作为剪贴底层" to "A pass-through group cannot be a clipping base yet",
        "当前图层组没有可变换的内容" to "This group has no content to transform",
        "请先选择组内的像素图层" to "Select a pixel layer inside the group first",
        "请先解锁组内所有图层及透明度" to "Unlock all layers and alpha inside the group first",
        "图层组变换超出像素内存限制" to "The group transform exceeds the pixel memory limit",
        "请先显示并解锁当前图层及父级" to "Show and unlock the current layer and its parent groups first",
        "父级必须为图层组" to "The parent must be a layer group",
        "图层组插入位置无效" to "Invalid group insertion position",
        "图层组名称无效" to "Invalid layer group name",
        "请选择需要分组的图层" to "Select layers to group",
        "请选择按底到顶顺序排列的连续同级图层" to "Select adjacent sibling layers in stack order",
        "请将完整剪贴链一起分组" to "Group the entire clipping chain together",
        "图层组不能移动到自身或子级" to "A group cannot move into itself or its descendants",
        "请选择图层组" to "Select a layer group",
        "请先解除组不透明度、蒙版、剪贴及混合效果再取消分组" to
            "Remove group opacity, mask, clipping and blend effects before ungrouping",
        "至少保留一个图层节点" to "Keep at least one layer node",
        "请选择连续同级图层" to "Select adjacent sibling layers",
        "图层组不能锁定透明像素" to "Alpha lock is available for pixel layers",
        "穿透图层组暂不支持不透明度、蒙版、剪贴和自身混合模式" to
            "Pass-through group opacity, masks, clipping and blend effects are not supported yet",
        "请先取消选区，再移动或变换图层组" to "Clear the selection before moving or transforming a group",
        "ORA 图层组嵌套超过上限" to "The ORA group nesting exceeds the limit",
        "ORA 图层组位置属性尚未支持" to "ORA group offsets are not supported yet",
        "ORA 根图层组包含不支持的属性" to "The ORA root stack contains unsupported properties",
        "ORA 图层组隔离属性无效" to "Invalid ORA group isolation",
        "ORA 穿透图层组暂不支持不透明度和自身混合模式" to
            "ORA pass-through group opacity and blend effects are not supported yet",
        "PSD 图层组标记无效" to "Invalid PSD group marker",
        "PSD 场景图层组尚未支持" to "PSD scene groups are not supported yet",
        "PSD 穿透混合模式仅适用于图层组" to "PSD pass-through blending is only valid for groups",
        "PSD 图层组边界包含无效属性" to "Invalid PSD group boundary properties",
        "PSD 图层组嵌套超过上限" to "The PSD group nesting exceeds the limit",
        "PSD 图层组起止标记不匹配" to "Unmatched PSD group boundaries",
        "导入 ASE 色板" to "Import ASE palette",
        "导出 ASE 色板" to "Export ASE palette",
        "ASE 色板已导入" to "ASE palette imported",
        "ASE 色板已导出" to "ASE palette exported",
        "导入色板" to "Import palette",
        "导出色板" to "Export palette",
        "色板已导入" to "Palette imported",
        "色板已导出" to "Palette exported",
        "仅导出颜色" to "Export colors",
        "GPL 保留颜色和名称，不能保存分组及专色类型。" to
            "GPL keeps colors and names. Groups and swatch types will be omitted.",
        "PAL 只保存颜色，不能保存名称、分组及专色类型。" to
            "PAL keeps colors only. Names, groups and swatch types will be omitted.",
        "色板文件超过大小限制" to "The palette exceeds the file size limit",
        "不是 GPL 或 JASC PAL 色板" to "This is not a GPL or JASC PAL palette",
        "尚未支持该 JASC PAL 版本" to "Unsupported JASC PAL version",
        "JASC PAL 颜色数量与文件内容不一致" to "The JASC PAL color count does not match its contents",
        "JASC PAL 颜色行只能包含三个 RGB 数值" to "A JASC PAL color row must contain three RGB values",
        "JASC PAL 必须使用 ASCII 文本" to "JASC PAL requires ASCII text",
        "GPL 色板列数必须在 0 到 255 之间" to "GPL palette columns must be between 0 and 255",
        "该格式无法保留色板元数据，需要明确允许扁平导出" to
            "This format cannot preserve the palette metadata. Choose Export colors to continue",
        "色板最多支持 256 色" to "Palettes support up to 256 colors",
        "色板 RGB 数值必须在 0 到 255 之间" to "Palette RGB values must be between 0 and 255",
        "色板 RGB 数值无效" to "Invalid palette RGB value",
        "色板整数无效" to "Invalid palette integer",
        "色板整数超过限制" to "A palette integer exceeds the limit",
        "文本色板名称必须是单行且首尾没有空白" to
            "Text palette names must be single lines without leading or trailing whitespace",
        "色板文件未完整结束" to "The palette file is incomplete",
        "色板文本包含无效字符" to "The palette text contains an invalid character",
        "色板文本不是有效 UTF-8" to "The palette text is not valid UTF-8",
        "当前平台暂不支持色板文件" to "Palette files are not available on this platform yet",
        "ASE 色板文件超过大小限制" to "The ASE palette exceeds the file size limit",
        "不是 Adobe Swatch Exchange 色板" to "This file is not an Adobe Swatch Exchange palette",
        "尚未支持该 ASE 版本" to "This ASE version is not supported yet",
        "ASE 色板块数量无效" to "Invalid ASE block count",
        "ASE 色板最多支持 256 色" to "ASE palettes support up to 256 colors",
        "尚未支持该 ASE 色板类型" to "This ASE swatch type is not supported yet",
        "ASE 色板分组超过限制" to "The ASE palette exceeds the group limit",
        "ASE 色板分组未匹配" to "Unmatched ASE palette group",
        "尚未支持该 ASE 色板块" to "This ASE block is not supported yet",
        "ASE 色板块长度无效" to "Invalid ASE block length",
        "ASE 色板数据或分组未完整结束" to "The ASE palette is incomplete",
        "ASE 色板不支持透明色" to "ASE palettes do not support transparent colors",
        "ASE 色板分组区间无效" to "Invalid ASE group range",
        "ASE 色板分组顺序无效" to "Invalid ASE group order",
        "尚未支持该 ASE 颜色模型" to "This ASE color model is not supported yet",
        "ASE LAB 颜色值无效" to "Invalid ASE LAB color",
        "ASE 颜色值超出范围" to "An ASE color value is out of range",
        "扩展选区" to "Expand selection",
        "收缩选区" to "Contract selection",
        "平滑选区" to "Smooth selection",
        "羽化选区" to "Feather selection",
        "选区已变化，请重新调整" to "The selection changed; refine it again",
        "选区参数无效" to "Invalid selection settings",
        "渐变映射" to "Gradient map",
        "渐变映射色标无效" to "Invalid gradient map stops",
        "添加色标" to "Add color stop",
        "删除色标" to "Remove color stop",
        "反转渐变" to "Reverse gradient",
        "重置渐变" to "Reset gradient",
        "色标位置" to "Stop position",
        "笔触" to "Stroke",
        "平滑笔触" to "Antialiased",
        "像素笔触" to "Pixel",
        "像素完美" to "Pixel perfect",
        "像素铅笔" to "Pixel pencil",
        "像素完美铅笔" to "Pixel-perfect pencil",
        "1 px 笔径使用像素完美线条" to "Pixel-perfect lines use a 1 px brush",
        "网格" to "Grid",
        "像素网格" to "Pixel grid",
        "瓦片网格" to "Tile grid",
        "网格宽度" to "Grid width",
        "网格高度" to "Grid height",
        "材质" to "Material",
        "光滑" to "Smooth",
        "石墨" to "Graphite",
        "炭粉" to "Charcoal",
        "刷毛" to "Bristles",
        "干燥刷毛" to "Dry bristles",
        "颜料" to "Pigment",
        "纤维" to "Fibers",
        "水彩湿边" to "Watercolor bloom",
        "数位板输入" to "Tablet input",
        "自动选择" to "Automatic",
        "自动优先使用 WinTab，驱动不可用时使用 Windows Ink。笔侧键按住落笔取色。" to
            "Automatic prefers WinTab and falls back to Windows Ink when unavailable. Hold the pen side button and tap to pick a color.",
        "参考图" to "References",
        "导入参考图" to "Import reference",
        "粘贴参考图" to "Paste reference",
        "收起参考图" to "Hide references",
        "显示参考图" to "Show references",
        "导入图片或粘贴参考图" to "Import or paste a reference",
        "取消读取参考图" to "Cancel loading",
        "镜像参考图" to "Mirror reference",
        "适合参考图" to "Fit reference",
        "移除参考图" to "Remove reference",
        "参考图视图" to "Reference view",
        "剪贴板图片" to "Clipboard image",
        "参考图文件过大" to "Reference file is too large",
        "参考图数据无效" to "Invalid reference image",
        "无法读取参考图" to "Could not read the reference image",
        "参考图支持 PNG、JPEG 和静态 WebP" to "References support PNG, JPEG and static WebP",
        "无法打开浏览器" to "Could not open the browser",
        "曲线" to "Curves",
        "曲线编辑器" to "Curve editor",
        "曲线控制点无效" to "Invalid curve points",
        "曲线直方图请求无效" to "Invalid histogram request",
        "红色通道" to "Red channel",
        "绿色通道" to "Green channel",
        "蓝色通道" to "Blue channel",
        "输入" to "Input",
        "输出" to "Output",
        "点击加点，拖动调整" to "Click to add, drag to adjust",
        "删除控制点" to "Delete point",
        "重置通道" to "Reset channel",
        "画布背景" to "Canvas background",
        "白色" to "White",
        "灰色" to "Gray",
        "透明棋盘格" to "Transparency grid",
        "仅影响显示" to "Display only",
        "画布显示选项无效" to "Invalid canvas display option",
        "图层混合" to "Layer blending",
        "图层已隐藏" to "Layer hidden",
        "原图对比" to "Compare original",
        "重置调整" to "Reset adjustment",
        "取消调整" to "Cancel adjustment",
        "确认调整" to "Apply adjustment",
        "调整已完成" to "Adjustment applied",
        "正在预览…" to "Updating preview…",
        "正在应用…" to "Applying…",
        "原图" to "Original",
        "预览" to "Preview",
        "请先确认或取消调整" to "Apply or cancel the adjustment first",
        "图层已变化，请重新调整" to "The layer changed. Start a new adjustment",
        "调整参数无效" to "Invalid adjustment settings",
        "涂抹" to "Smudge",
        "涂抹强度" to "Smudge strength",
        "强度压感" to "Strength pressure",
        "涂抹笔尖过大" to "Smudge tip is too large",
        "作品" to "Your work",
        "作品首页" to "Workspace",
        "空白画布" to "Blank canvas",
        "启动时" to "On startup",
        "打开作品" to "Open artwork",
        "未命名" to "Untitled",
        "有未保存的改动" to "Unsaved changes",
        "当前画布" to "Current canvas",
        "旋转视图" to "Rotate view",
        "镜像视图" to "Mirror view",
        "向左旋转" to "Rotate left",
        "向右旋转" to "Rotate right",
        "回正" to "Reset angle",
        "Shift + 滚轮旋转" to "Shift + scroll to rotate",
        "查找作品" to "Search artwork",
        "名称" to "Name",
        "最近" to "Recent",
        "从一张空白画布开始" to "Start with a blank canvas",
        "没有找到作品" to "No matching artwork",
        "作品仅在手动保存时写入文件" to "Your work is saved only when you choose Save",
        "作品选项" to "Artwork options",
        "从列表移除" to "Remove from list",
        "保存这份作品？" to "Save your changes?",
        "未保存的改动会丢失。" to "Unsaved changes will be lost.",
        "不保存" to "Don't save",
        "另存为" to "Save as",
        "作品列表无法读取" to "Could not read the artwork list",
        "作品已打开或保存，但作品列表更新失败" to "The file is ready, but the artwork list could not be updated",
        "找不到这份作品，请重新选择文件" to "File not found. Choose its new location.",
        "无法打开这份作品，请重新选择文件" to "Could not open this artwork. Choose the file again.",
        "支持 podor、PSD、ORA、PNG、JPEG 和 WebP。" to "Supports podor, PSD, ORA, PNG, JPEG and WebP.",
        "PSD 支持 8 位 RGB 像素图层，颜色按 sRGB 读取。" to
            "PSD supports 8-bit RGB pixel layers. Colors are read as sRGB.",
        "PSD、ORA 仅保留画布内的平面图层。" to "PSD and ORA import flat layers within the canvas bounds.",
        "导入为图层" to "Import as layer",
        "画布大小" to "Canvas size",
        "图像尺寸" to "Image size",
        "锁定比例" to "Lock proportions",
        "平滑" to "Smooth",
        "像素" to "Pixel",
        "适合绘画与照片" to "Paintings and photos",
        "保留像素硬边" to "Keep pixel edges",
        "所有图层一起缩放，可撤销。" to "Scales every layer. You can undo this.",
        "缩放图像会超出撤销内存限制" to "Scaling would exceed the undo memory limit",
        "应用" to "Apply",
        "定位" to "Anchor",
        "左上" to "Top left",
        "上方" to "Top",
        "右上" to "Top right",
        "左侧" to "Left",
        "居中" to "Center",
        "右侧" to "Right",
        "左下" to "Bottom left",
        "下方" to "Bottom",
        "右下" to "Bottom right",
        "新增区域透明，笔迹大小不变。" to "New space is transparent. Stroke size stays unchanged.",
        "边界外的像素会裁切，可撤销。" to "Pixels outside the boundary will be cropped. You can undo this.",
        "画布定位无效" to "The canvas anchor is invalid",
        "画布已变化，请重新调整尺寸" to "The canvas has changed. Adjust its size again",
        "调整画布会超出撤销内存限制" to "Resizing the canvas would exceed the undo memory limit",
        "图像已导入为图层" to "Image imported as a layer",
        "导入图层请选择 PNG、JPEG 或静态 WebP 图片" to
            "Choose a PNG, JPEG or static WebP image to import as a layer",
        "暂不支持动画 PNG，请先导出为静态图片" to "Animated PNG is not supported; export a still image first",
        "导入图层超过撤销内存限制" to "The imported layer exceeds the undo memory limit",
        "导入图层数据无效" to "The layer import data is invalid",
        "关于与更新" to "About & updates",
        "稳定版" to "Stable",
        "软件更新" to "Software update",
        "正在检查更新" to "Checking for updates",
        "已是最新版本" to "You're up to date",
        "发现新版本" to "Update available",
        "正在下载" to "Downloading",
        "安装包已就绪" to "Ready to install",
        "暂时无法更新" to "Update unavailable",
        "打开下载文件夹" to "Show download folder",
        "下载更新" to "Download update",
        "重新检查" to "Check again",
        "重试" to "Retry",
        "检查更新" to "Check for updates",
        "更新内容" to "What's new",
        "连接失败，请稍后重试" to "Could not connect. Please try again.",
        "更新信息无效" to "Invalid update information",
        "安装包校验失败，请重新下载" to "Verification failed. Download again.",
        "无法保存安装包，请检查磁盘空间" to "Could not save the installer. Check available disk space.",
        "更新通道尚未配置" to "Update channel is not configured",
        "工作台" to "Studio",
        "导出图像" to "Export image",
        "导出" to "Export",
        "透明背景" to "Transparent background",
        "JPEG 使用白色背景" to "JPEG uses a white background",
        "图像质量" to "Image quality",
        "高兼容" to "Compatible",
        "无损" to "Lossless",
        "JPEG 已导出" to "JPEG exported",
        "WebP 已导出" to "WebP exported",
        "ORA 已导出" to "ORA exported",
        "TIFF 已导出" to "TIFF exported",
        "BMP 已导出" to "BMP exported",
        "PSD 已导出" to "PSD exported",
        "PSD 文件超过大小限制" to "PSD file exceeds the size limit",
        "保留图层" to "Layers",
        "保留图层与透明度" to "Layers and transparency",
        "图层名称包含不支持的字符" to "Layer name contains unsupported characters",
        "缩略图生成失败" to "Could not generate thumbnails",
        "画笔" to "Brush",
        "笔刷库" to "Brush library",
        "橡皮" to "Eraser",
        "矩形选区" to "Marquee",
        "选区" to "Selection",
        "剪贴板" to "Clipboard",
        "变换图层" to "Transform layer",
        "渐变" to "Gradient",
        "线性渐变" to "Linear gradient",
        "径向渐变" to "Radial gradient",
        "反转渐变" to "Reverse gradient",
        "淡出到透明" to "Fade to transparent",
        "渐变不透明度" to "Gradient opacity",
        "确认渐变" to "Apply gradient",
        "取消渐变" to "Cancel gradient",
        "渐变已完成" to "Gradient applied",
        "渐变参数无效" to "Invalid gradient parameters",
        "渐变会超出撤销内存限制" to "Gradient exceeds the undo memory limit",
        "画布已改变，请重新绘制渐变" to "The canvas changed. Draw the gradient again",
        "请先确认或取消渐变" to "Apply or cancel the gradient first",
        "水平翻转图层" to "Flip layer horizontally",
        "垂直翻转图层" to "Flip layer vertically",
        "顺时针旋转 90°" to "Rotate 90° clockwise",
        "像素采样" to "Pixel sampling",
        "重置变换" to "Reset transform",
        "取消变换" to "Cancel transform",
        "确认变换" to "Apply transform",
        "图层变换已完成" to "Layer transformed",
        "图层变换参数无效" to "Invalid layer transform",
        "当前图层没有可变换的内容" to "This layer contains no pixels to transform",
        "图层变换会超出撤销内存限制" to "Layer transform exceeds the undo memory limit",
        "图层已变化，请重新开始变换" to "The layer changed, please restart the transform",
        "请先取消选区，再变换图层" to "Clear the selection before transforming the layer",
        "请先确认或取消图层变换" to "Apply or cancel the layer transform first",
        "复制当前图层" to "Copy active layer",
        "复制可见画面" to "Copy visible",
        "剪切" to "Cut",
        "粘贴为新图层" to "Paste as new layer",
        "粘贴的图像" to "Pasted image",
        "已复制图片" to "Image copied",
        "已剪切，可撤销" to "Cut, undo available",
        "已粘贴到新图层" to "Pasted as new layer",
        "当前平台暂不支持图片剪贴板" to "Image clipboard is unavailable on this platform",
        "剪贴板中没有图片" to "The clipboard contains no image",
        "剪贴板正被占用，请稍后重试" to "Clipboard is busy, please try again",
        "剪贴板图片过大" to "Clipboard image is too large",
        "剪贴板图片尺寸超出限制" to "Clipboard image dimensions exceed the limit",
        "剪贴板图片数据无效" to "Invalid clipboard image",
        "剪贴板图片位置无效" to "Invalid clipboard image position",
        "剪贴板图片没有可见内容" to "Clipboard image contains no visible pixels",
        "剪贴板图片尚未就绪" to "Clipboard image is not ready",
        "读取剪贴板图片失败" to "Could not read the clipboard image",
        "复制图像失败" to "Could not copy the image",
        "复制选项无效" to "Invalid copy option",
        "选中区域没有可复制的内容" to "The selected area contains no pixels to copy",
        "剪切内容超过撤销内存限制" to "Cut exceeds the undo memory limit",
        "椭圆选区" to "Ellipse selection",
        "自由套索" to "Freehand lasso",
        "魔棒选区" to "Magic wand",
        "全部笔刷" to "All brushes",
        "收藏的笔刷" to "Favorites",
        "扩展笔刷" to "Extensions",
        "搜索笔刷" to "Search brushes",
        "清除搜索" to "Clear search",
        "收藏笔刷" to "Favorite brush",
        "取消收藏笔刷" to "Unfavorite brush",
        "点亮星标，收藏常用笔刷" to "Star a brush to keep it here",
        "没有匹配的笔刷" to "No matching brushes",
        "保存笔刷" to "Save brush",
        "另存笔刷副本" to "Save a copy",
        "魔棒设置" to "Magic wand options",
        "容差" to "Tolerance",
        "仅连续区域" to "Contiguous only",
        "取样所有可见图层" to "Sample visible layers",
        "取样位置超出画布" to "Sample point is outside the canvas",
        "连续区域过于复杂，请缩小图像后重试" to "Region is too complex. Reduce the image size and try again.",
        "套索路径无效或过长" to "Invalid or excessive lasso path",
        "选区超出画布或为空" to "Selection is empty or outside the canvas",
        "选区为空" to "Selection is empty",
        "选区参数无效" to "Invalid selection settings",
        "填充" to "Fill",
        "取色" to "Eyedropper",
        "移动" to "Pan",
        "移动画布" to "Pan canvas",
        "颜色" to "Color",
        "调色盘" to "Color wheel",
        "图层" to "Layers",
        "添加蒙版" to "Add mask",
        "白色蒙版" to "Reveal all",
        "黑色蒙版" to "Hide all",
        "从选区创建蒙版" to "From selection",
        "编辑图层" to "Edit layer pixels",
        "编辑蒙版" to "Edit mask",
        "启用蒙版" to "Enable mask",
        "停用蒙版" to "Disable mask",
        "链接蒙版" to "Link mask",
        "解除蒙版链接" to "Unlink mask",
        "反相蒙版" to "Invert mask",
        "应用蒙版" to "Apply mask",
        "删除蒙版" to "Delete mask",
        "蒙版设置" to "Mask settings",
        "图层编辑目标已变化，请重新移动" to "The editing target changed. Start the move again",
        "图层编辑目标已变化，请重新变换" to "The editing target changed. Start the transform again",
        "当前图层没有蒙版" to "This layer has no mask",
        "当前图层已有蒙版" to "This layer already has a mask",
        "请先启用蒙版" to "Enable the mask first",
        "蒙版超过内存限制" to "The mask exceeds the memory limit",
        "蒙版尺寸超出限制" to "The mask dimensions exceed the limit",
        "蒙版数据无效" to "Invalid mask data",
        "请先显示并解锁当前图层" to "Show and unlock the current layer first",
        "蒙版移动越界" to "The mask cannot move beyond this range",
        "蒙版没有可变换的内容" to "The mask has no content to transform",
        "蒙版变换参数无效" to "Invalid mask transform",
        "蒙版不支持涂抹笔" to "Smudging is not available for masks yet",
        "蒙版填色不支持合并图层取样" to "Merged sampling is not available for mask fills",
        "请先切换到图层像素再使用渐变" to "Select the layer pixels to use gradients",
        "请先切换到图层像素再绘制渐变" to "Select the layer pixels to use gradients",
        "请先切换到图层像素再使用调整" to "Select the layer pixels to use adjustments",
        "请先切换到图层像素" to "Select the layer pixels first",
        "请先切换到图层像素再调整颜色" to "Select the layer pixels to adjust colors",
        "ORA 不能保留独立图层蒙版，请改用 podor 工程或 PSD" to
            "ORA cannot preserve editable layer masks. Save as podor or PSD",
        "ORA 不能保留剪贴蒙版，请改用 podor 工程或 PSD" to
            "ORA cannot preserve clipping masks. Save as podor or PSD",
        "图层已变化，请重新设置剪贴蒙版" to "The layer changed. Set the clipping mask again",
        "底层图层不能设置为剪贴蒙版" to "The bottom layer cannot be a clipping mask",
        "请先统一剪贴蒙版与底层的可见性，再合并可见图层" to
            "Show or hide the entire clipping group before merging visible layers",
        "图层预览超过内存限制" to "The layer preview exceeds the memory limit",
        "PSD 全局蒙版尚未支持，请先应用全局蒙版" to
            "PSD global masks are not supported yet. Apply the global mask first",
        "PSD 目前支持普通像素蒙版，请先应用矢量蒙版或蒙版密度、羽化参数" to
            "Only pixel masks are supported. Apply vector masks, mask density and feathering first",
        "锁定透明度" to "Lock alpha",
        "解除透明度锁定" to "Unlock alpha",
        "锁定图层" to "Lock layer",
        "解锁图层" to "Unlock layer",
        "图层已锁定，请先解锁" to "Unlock this layer before editing",
        "请先解除透明度锁定" to "Unlock alpha first",
        "请先解锁要合并的图层" to "Unlock the layers before merging",
        "工程版本不受支持，请更新 podor" to "Unsupported project version. Update podor to open it.",
        "混合模式" to "Blend mode",
        "正常" to "Normal",
        "正片叠底" to "Multiply",
        "滤色" to "Screen",
        "叠加" to "Overlay",
        "柔光" to "Soft light",
        "变暗" to "Darken",
        "变亮" to "Lighten",
        "差值" to "Difference",
        "调整" to "Adjust",
        "设置" to "Settings",
        "语言" to "Language",
        "外观" to "Appearance",
        "通用" to "General",
        "深色" to "Dark",
        "浅色" to "Light",
        "快捷键" to "Shortcuts",
        "插件" to "Plugins",
        "关闭" to "Close",
        "收起面板" to "Hide panel",
        "展开面板" to "Show panel",
        "拖动缩略图排序" to "Drag thumbnail to reorder",
        "图层已变化，请重新排序" to "The layers changed. Drag again",
        "移动图层" to "Move layer",
        "平移画布" to "Pan canvas",
        "超出画布的部分会裁切" to "Content outside the canvas is clipped",
        "取消移动" to "Cancel move",
        "准备图层…" to "Preparing layer…",
        "请先取消选区，再移动图层" to "Deselect before moving the layer",
        "图层已变化，请重新移动" to "The layer changed. Move it again",
        "移动距离超出画布尺寸" to "Move exceeds canvas dimensions",
        "图层内容过多，移动会超出撤销内存限制" to "This move would exceed the undo memory limit",
        "最小化" to "Minimize",
        "最大化" to "Maximize",
        "还原窗口" to "Restore window",
        "编辑笔刷" to "Brush editor",
        "大小" to "Size",
        "不透明度" to "Opacity",
        "墨水笔" to "Ink",
        "勾线笔" to "Liner",
        "稳笔" to "Stabilization",
        "笔尖" to "Tip",
        "压感" to "Pressure",
        "响应" to "Response",
        "轻压" to "Light pressure",
        "重压" to "Firm pressure",
        "轻柔" to "Soft",
        "线性" to "Linear",
        "有力" to "Firm",
        "压感曲线" to "Pressure curve",
        "粗细压感" to "Size pressure",
        "透明度压感" to "Opacity pressure",
        "压感墨笔" to "Pressure ink",
        "薄涂笔" to "Glaze",
        "柳叶笔" to "Lasso fill",
        "尖锋笔" to "Tapered ink",
        "圈选填色" to "Fill shape",
        "圈选擦除" to "Erase shape",
        "套索填色参数无效或路径过长" to "Invalid lasso fill settings or excessive path",
        "套索填色会超出撤销内存限制" to "Lasso fill exceeds the undo memory limit",
        "柳条笔" to "Willow",
        "混合笔" to "Mixer",
        "油彩笔" to "Oils",
        "纸纹笔" to "Paper grain",
        "水彩纸" to "Watercolor paper",
        "柳叶" to "Leaf",
        "排齿" to "Comb",
        "纸纹" to "Paper texture",
        "调色混合" to "Paint mixing",
        "马克笔" to "Marker",
        "柔边笔" to "Soft",
        "铅笔" to "Pencil",
        "炭笔" to "Charcoal",
        "喷枪" to "Airbrush",
        "水彩" to "Watercolor",
        "斜头笔" to "Chisel",
        "平刷" to "Flat",
        "缎带" to "Ribbon",
        "干刷" to "Dry brush",
        "排线笔" to "Hatching",
        "跟随笔画方向" to "Follow stroke direction",
        "点描" to "Stipple",
        "手指绘画" to "Finger drawing",
        "名称" to "Name",
        "圆形" to "Round",
        "扁平" to "Flat",
        "硬度" to "Hardness",
        "笔尖比例" to "Aspect",
        "角度" to "Angle",
        "颗粒" to "Grain",
        "间距" to "Spacing",
        "保存为新笔刷" to "Save as new brush",
        "删除笔刷" to "Delete brush",
        "确认删除笔刷" to "Confirm brush deletion",
        "完成" to "Done",
        "取消" to "Cancel",
        "按下快捷键" to "Press a shortcut",
        "恢复默认" to "Reset defaults",
        "仅支持字母、数字和组合键" to "Use a letter or digit with optional modifiers",
        "快捷键已被占用" to "Shortcut already in use",
        "导入笔刷包" to "Import brush pack",
        "导出笔刷包" to "Export brush pack",
        "导入 JSON 笔刷扩展包" to "Import a JSON brush pack",
        "移除插件" to "Remove plugin",
        "自定义笔刷" to "Custom brushes",
        "删除笔刷" to "Delete brush",
        "自由创作" to "Untitled",
        "工程菜单" to "Project",
        "新建画布" to "New canvas",
        "打开工程 / 图片" to "Open project / image",
        "保存工程" to "Save project",
        "清空当前图层" to "Clear layer",
        "快捷键与手势" to "Shortcuts & gestures",
        "取消选区" to "Deselect",
        "上一件作品" to "Previous artwork",
        "下一件作品" to "Next artwork",
        "缩放" to "Zoom",
        "放大画布" to "Zoom in",
        "缩小画布" to "Zoom out",
        "减小笔刷" to "Smaller brush",
        "增大笔刷" to "Larger brush",
        "快速调节" to "Quick controls",
        "长按数值并左右拖动可细调" to "Hold a value and drag to fine-tune",
        "色相" to "Hue",
        "撤销" to "Undo",
        "重做" to "Redo",
        "导出" to "Export",
        "适合窗口" to "Fit canvas",
        "更多工具" to "More tools",
        "图层与工作台" to "Layers & studio",
        "画笔、颜色与图层" to "Studio",
        "关闭工作台" to "Close studio",
        "选择颜色" to "Color picker",
        "饱和度与明度色板" to "Saturation and brightness",
        "HEX 颜色" to "HEX color",
        "工作室色卡" to "Studio palette",
        "新建选区" to "Replace selection",
        "添加到选区" to "Add to selection",
        "从选区减去" to "Subtract from selection",
        "与选区相交" to "Intersect selection",
        "反选" to "Invert selection",
        "请先创建选区" to "Create a selection first",
        "选区为空" to "Selection is empty",
        "选区已更新" to "Selection updated",
        "我的色卡" to "My palette",
        "从画布提取颜色" to "Extract canvas colors",
        "保存当前颜色" to "Save current color",
        "移除此颜色" to "Remove this color",
        "画布上没有可提取的颜色" to "No painted colors to extract",
        "已提取画布颜色" to "Canvas colors extracted",
        "色卡空间不足，请先移除一些颜色" to "Palette is full. Remove some colors first",
        "色卡数量无效" to "Invalid palette size",
        "请先结束笔画" to "Finish the current stroke first",
        "饱和度" to "Saturation",
        "明度" to "Value",
        "亮度" to "Brightness",
        "对比度" to "Contrast",
        "新建图层" to "Add layer",
        "图层设置" to "Layer settings",
        "图层名称" to "Layer name",
        "复制图层" to "Duplicate layer",
        "合并可见图层" to "Merge visible layers",
        "合并图层" to "Merged layer",
        "至少需要两个可见图层" to "At least two visible layers are needed",
        "图层内容过多，合并会超出撤销内存限制" to "Merging these layers would exceed the undo memory limit",
        "图层不透明度" to "Layer opacity",
        "重命名" to "Rename",
        "上移图层" to "Move up",
        "下移图层" to "Move down",
        "删除图层" to "Delete layer",
        "重命名图层" to "Rename layer",
        "保存" to "Save",
        "明暗与色彩" to "Tone & color",
        "仅作用于当前图层的选区" to "Active layer selection",
        "作用于当前图层" to "Active layer",
        "应用色彩调整" to "Apply tone",
        "高斯模糊" to "Gaussian blur",
        "半径" to "Radius",
        "应用模糊" to "Apply blur",
        "填充设置" to "Fill",
        "颜色容差" to "Tolerance",
        "点击应用后生效，可随时撤销。" to "Apply, then undo at any time.",
        "选择填充工具，轻点连通区域。颜色与不透明度沿用画笔设置。" to "Tap a connected area. Uses brush color and opacity.",
        "请先保存当前工程，新画布会替换当前内容。" to "Save your work before replacing the canvas.",
        "打开工程或图片" to "Open project or image",
        "打开后会替换当前画布，重要改动请先保存。" to "Save your work before opening another canvas.",
        "选择文件" to "Choose file",
        "清空当前图层？" to "Clear this layer?",
        "清空后仍可撤销。" to "You can undo this action.",
        "清空" to "Clear",
        "暂时无法完成" to "Unable to complete",
        "知道了" to "OK",
        "宽度" to "Width",
        "高度" to "Height",
        "安装前会退出 podor，完成后重新打开，不会自动重启电脑。" to
            "podor will close for installation and open afterward. Your computer will not restart automatically.",
        "安装并打开" to "Install and open",
        "下载文件夹" to "Downloads folder",
        "无法启动安装程序，请打开下载文件夹重试" to "Could not start setup. Open the download folder to try again.",
        "当前平台不支持安装更新" to "Installing updates is not supported on this platform",
        "创建" to "Create",
        "自定义尺寸" to "Custom size",
        "尺寸超出限制" to "Size exceeds limits",
        "横向画布" to "Landscape",
        "方形画布" to "Square",
        "竖向画布" to "Portrait",
        "高清画布" to "HD",
        "交换宽高" to "Swap dimensions",
        "准备画布…" to "Preparing canvas…",
        "画布已就绪" to "Canvas ready",
        "工程已打开" to "Project opened",
        "PNG 已导出" to "PNG exported",
        "工程已保存" to "Project saved",
        "笔刷包已导入" to "Brush pack imported",
        "笔刷包过大" to "Brush pack is too large",
        "笔刷包参数无效" to "Invalid brush pack",
        "设置参数无效" to "Invalid settings",
        "插件数量超过限制" to "Plugin limit reached",
        "设置文件无法读取，已使用默认设置" to "Could not read settings; defaults loaded",
        "填充位置不在选区内" to "Fill position is outside the selection",
        "请先显示当前图层" to "Show the active layer first",
        "已达到图层上限" to "Layer limit reached",
        "至少保留一个图层" to "Keep at least one layer",
        "画布尺寸超出限制" to "Canvas size exceeds limits",
        "不是有效的podor工程" to "Not a valid podor project",
        "文件过大" to "File is too large",
        "请选择 podor、PSD、ORA 工程或 PNG、JPEG、WebP 图片" to
            "Choose a podor, PSD or ORA project, or a PNG, JPEG or WebP image",
        "ORA 压缩包已损坏" to "The ORA archive is damaged",
        "ORA 文件目录无效" to "The ORA file directory is invalid",
        "ORA 类型信息无效" to "The ORA media type is invalid",
        "这不是有效的 ORA 文件" to "This is not a valid ORA file",
        "ORA 图层信息无效" to "The ORA layer information is invalid",
        "ORA 图层数量超过上限" to "The ORA file exceeds the layer limit",
        "暂不支持含图层组的 ORA，请先在原软件中取消分组" to
            "ORA layer groups are not supported yet. Ungroup them in the original app first",
        "ORA 含有暂不支持的图层类型" to "The ORA file contains unsupported layer types",
        "ORA 图层名称过长" to "An ORA layer name is too long",
        "ORA 图层不透明度无效" to "An ORA layer opacity is invalid",
        "ORA 图层可见性无效" to "An ORA layer visibility is invalid",
        "ORA 使用了暂不支持的混合模式" to "The ORA file uses an unsupported blend mode",
        "ORA 缺少图层图像" to "An ORA layer image is missing",
        "ORA 图层路径无效" to "An ORA layer path is invalid",
        "ORA 图层必须为 PNG 图片" to "ORA layers must be PNG images",
        "ORA 图层图像无法读取" to "An ORA layer image cannot be read",
        "ORA 图层图像过大" to "An ORA layer image is too large",
        "ORA 图层图像已损坏" to "An ORA layer image is damaged",
        "ORA 文件目录过大或格式不受支持" to "The ORA directory is too large or unsupported",
        "ORA 缺少必要文件" to "The ORA file is missing required entries",
        "ORA 图层信息过大" to "The ORA layer metadata is too large",
        "ORA 文件已损坏" to "The ORA file is damaged",
        "ORA 图层属性无效" to "An ORA layer property is invalid",
        "ORA 缺少画布尺寸" to "The ORA canvas dimensions are missing",
        "ORA 图层 PNG 无法读取" to "An ORA layer PNG cannot be read",
        "ORA 图层不支持动画 PNG" to "Animated PNG layers are not supported in ORA",
        "ORA 图层 PNG 已损坏" to "An ORA layer PNG is damaged",
        "ORA 图层 PNG 颜色格式不受支持" to "An ORA layer PNG color format is unsupported",
        "PSD 文件已损坏" to "The PSD file is damaged",
        "PSD 包含尚未支持的图层属性，请先栅格化特效、文字或智能对象" to
            "This PSD has unsupported layer properties. Rasterize effects, text or smart objects first",
        "暂不支持 PSB，请另存为 PSD" to "PSB is not supported. Save as PSD first",
        "PSD 仅支持 RGB 和透明度通道，请移除额外通道" to
            "PSD supports RGB and transparency channels. Remove extra channels first",
        "PSD 目前支持 8 位 RGB，请先转换颜色模式" to
            "PSD currently supports 8-bit RGB. Convert the color mode first",
        "PSD 图层数量超出限制" to "The PSD has too many layers",
        "PSD 解码像素超过限制" to "PSD decoding exceeds the pixel limit",
        "PSD 合成图含额外通道，请保存包含像素图层的 PSD" to
            "The merged PSD has extra channels. Save a PSD with pixel layers",
        "PSD 图层尺寸超出限制" to "A PSD layer exceeds the size limit",
        "PSD 图层组尚未支持，请先合并图层组" to "PSD groups are not supported. Merge layer groups first",
        "PSD 包含尚未支持的混合模式" to "The PSD uses an unsupported blend mode",
        "PSD 剪贴蒙版标记无效" to "Invalid PSD clipping mask flag",
        "PSD 混合颜色带尚未支持，请先栅格化该图层" to
            "PSD Blend If ranges are not supported. Rasterize the layer first",
        "PSD 图层名称过长" to "A PSD layer name is too long",
        "PSD 压缩方式不受支持" to "The PSD compression method is unsupported",
        "图片数据损坏或格式不受支持" to "Image is damaged or its format is unsupported",
        "暂不支持动态 WebP，请先导出为静态图片" to "Animated WebP is not supported; export a still image first",
        "图片解码超过内存限制" to "Image decoding exceeds the memory limit",
        "无法读取图片方向" to "Could not read image orientation",
        "工程文件已损坏" to "Project file is damaged",
        "导入的图像" to "Imported image",
        "对称绘画" to "Symmetry",
        "对称绘画适用于画笔和橡皮" to "Symmetry is available for brushes and erasers",
        "关闭对称" to "Symmetry off",
        "左右对称" to "Vertical symmetry",
        "上下对称" to "Horizontal symmetry",
        "双轴对称" to "Quadrant symmetry",
        "横向位置" to "Horizontal position",
        "纵向位置" to "Vertical position",
        "显示对称轴" to "Show symmetry guides",
        "对称轴居中" to "Center symmetry axes",
        "对称轴位置无效" to "Invalid symmetry axis position",
        "涂抹暂不支持对称绘画" to "Symmetry is not yet available for smudging",
        "新建调整图层" to "New adjustment layer",
        "编辑调整图层" to "Edit adjustment layer",
        "调整图层" to "Adjustment layer",
        "烘焙副本" to "Flattened copy",
        "导出合成副本" to "Export a flattened copy",
        "合并副本中的所有图层" to "Flatten all layers in the exported copy",
        "调整图层不支持此类型" to "This adjustment layer type is not supported",
        "请先解锁调整图层及父级" to "Unlock the adjustment layer and its ancestors first",
        "请选择调整图层" to "Select an adjustment layer",
        "调整图层暂仅支持普通混合模式" to "Adjustment layers currently support Normal blending only",
        "调整图层不能作为剪贴底层" to "Adjustment layers cannot be clipping bases",
        "蒙版堆栈" to "Mask stack",
        "蒙版" to "Mask",
        "应用全部蒙版" to "Apply all masks",
        "蒙版名称" to "Mask name",
        "复制蒙版" to "Duplicate mask",
        "前移蒙版" to "Move mask earlier",
        "后移蒙版" to "Move mask later",
        "蒙版编辑目标已变化，请重新移动" to "The mask target changed; prepare the move again",
        "蒙版编辑目标已变化，请重新变换" to "The mask target changed; prepare the transform again",
        "新建矢量图层" to "New vector layer",
        "矢量图层" to "Vector layer",
        "矢量工具" to "Vector tools",
        "矢量对象" to "Vector objects",
        "编辑节点" to "Edit nodes",
        "钢笔路径" to "Pen path",
        "矩形" to "Rectangle",
        "椭圆" to "Ellipse",
        "直线" to "Line",
        "确认矢量编辑" to "Confirm vector edit",
        "取消矢量编辑" to "Cancel vector edit",
        "请先确认或取消矢量编辑" to "Confirm or cancel the vector edit first",
        "转换为像素图层" to "Rasterize layer",
        "对象可见性" to "Object visibility",
        "填充颜色" to "Fill color",
        "描边颜色" to "Stroke color",
        "移除填充" to "Remove fill",
        "移除描边" to "Remove stroke",
        "删除矢量对象" to "Delete vector object",
        "矢量对象设置" to "Vector object settings",
        "上移对象" to "Move object up",
        "下移对象" to "Move object down",
        "奇偶填充" to "Even-odd fill",
        "闭合路径" to "Close path",
        "描边宽度" to "Stroke width",
        "端点" to "Line cap",
        "连接" to "Line join",
        "仅导出当前矢量图层" to "Export the current vector layer only",
        "工具选项" to "Tool options",
        "动画" to "Animation",
        "视图" to "View",
        "启用动画" to "Enable animation",
        "界面" to "Interface",
        "工具栏位置" to "Toolbar position",
        "面板位置" to "Panel position",
        "界面密度" to "Interface density",
        "紧凑" to "Compact",
        "标准" to "Standard",
        "宽松" to "Comfortable",
        "界面缩放" to "Interface scale",
        "缩小界面" to "Decrease interface scale",
        "放大界面" to "Increase interface scale",
        "减少动态效果" to "Reduce motion",
        "工具顺序与显示" to "Tool order and visibility",
        "隐藏的工具可在更多工具中打开" to "Hidden tools remain available in More tools",
        "上移工具" to "Move tool up",
        "下移工具" to "Move tool down",
        "隐藏工具" to "Hide tool",
        "显示工具" to "Show tool",
        "恢复默认界面" to "Reset workspace layout",
        "工具栏" to "Toolbar",
        "面板" to "Panel",
        "顶部" to "Top",
        "底部" to "Bottom",
    )
