package app.podor.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import app.podor.domain.Language

val LocalLanguage = staticCompositionLocalOf { Language.Chinese }

@Composable fun tr(value: String): String = trValue(value, LocalLanguage.current)

fun trValue(value: String, language: Language): String {
    if (language == Language.Chinese) return value
    english[value]?.let {
        return it
    }
    val divider = value.indexOf(" · ")
    if (divider > 0)
        return trValue(value.substring(0, divider), language) + value.substring(divider)
    if (value.startsWith("图层 ")) return "Layer " + value.removePrefix("图层 ")
    if (value.startsWith("颜色 #")) return "Color #" + value.removePrefix("颜色 #")
    if (value.startsWith("隐藏 ")) return "Hide " + value.removePrefix("隐藏 ")
    if (value.startsWith("显示 ")) return "Show " + value.removePrefix("显示 ")
    return value
}

private val english =
    mapOf(
        "原图对比" to "Compare original",
        "重置调整" to "Reset adjustment",
        "取消调整" to "Cancel adjustment",
        "确认调整" to "Apply adjustment",
        "调整已完成" to "Adjustment applied",
        "正在预览…" to "Updating preview…",
        "正在应用…" to "Applying…",
        "原图" to "Original",
        "预览" to "Preview",
        "请先确认或取消调整" to "Apply or cancel the adjustment first",
        "图层已变化，请重新调整" to "The layer changed. Start a new adjustment",
        "调整参数无效" to "Invalid adjustment settings",
        "涂抹" to "Smudge",
        "涂抹强度" to "Smudge strength",
        "强度压感" to "Strength pressure",
        "涂抹笔尖过大" to "Smudge tip is too large",
        "作品" to "Your work",
        "作品首页" to "Workspace",
        "空白画布" to "Blank canvas",
        "启动时" to "On startup",
        "打开作品" to "Open artwork",
        "未命名" to "Untitled",
        "有未保存的改动" to "Unsaved changes",
        "当前画布" to "Current canvas",
        "旋转视图" to "Rotate view",
        "镜像视图" to "Mirror view",
        "向左旋转" to "Rotate left",
        "向右旋转" to "Rotate right",
        "回正" to "Reset angle",
        "Shift + 滚轮旋转" to "Shift + scroll to rotate",
        "查找作品" to "Search artwork",
        "名称" to "Name",
        "最近" to "Recent",
        "从一张空白画布开始" to "Start with a blank canvas",
        "没有找到作品" to "No matching artwork",
        "作品仅在手动保存时写入文件" to "Your work is saved only when you choose Save",
        "作品选项" to "Artwork options",
        "从列表移除" to "Remove from list",
        "保存这份作品？" to "Save your changes?",
        "未保存的改动会丢失。" to "Unsaved changes will be lost.",
        "不保存" to "Don't save",
        "另存为" to "Save as",
        "作品列表无法读取" to "Could not read the artwork list",
        "作品已打开或保存，但作品列表更新失败" to "The file is ready, but the artwork list could not be updated",
        "找不到这份作品，请重新选择文件" to "File not found. Choose its new location.",
        "无法打开这份作品，请重新选择文件" to "Could not open this artwork. Choose the file again.",
        "支持 podor、PSD、ORA、PNG、JPEG 和 WebP。" to "Supports podor, PSD, ORA, PNG, JPEG and WebP.",
        "PSD 支持 8 位 RGB 像素图层，颜色按 sRGB 读取。" to "PSD supports 8-bit RGB pixel layers. Colors are read as sRGB.",
        "PSD、ORA 仅保留画布内的平面图层。" to "PSD and ORA import flat layers within the canvas bounds.",
        "导入为图层" to "Import as layer",
        "画布大小" to "Canvas size",
        "图像尺寸" to "Image size",
        "锁定比例" to "Lock proportions",
        "平滑" to "Smooth",
        "像素" to "Pixel",
        "适合绘画与照片" to "Paintings and photos",
        "保留像素硬边" to "Keep pixel edges",
        "所有图层一起缩放，可撤销。" to "Scales every layer. You can undo this.",
        "缩放图像会超出撤销内存限制" to "Scaling would exceed the undo memory limit",
        "应用" to "Apply",
        "定位" to "Anchor",
        "左上" to "Top left",
        "上方" to "Top",
        "右上" to "Top right",
        "左侧" to "Left",
        "居中" to "Center",
        "右侧" to "Right",
        "左下" to "Bottom left",
        "下方" to "Bottom",
        "右下" to "Bottom right",
        "新增区域透明，笔迹大小不变。" to "New space is transparent. Stroke size stays unchanged.",
        "边界外的像素会裁切，可撤销。" to "Pixels outside the boundary will be cropped. You can undo this.",
        "画布定位无效" to "The canvas anchor is invalid",
        "画布已变化，请重新调整尺寸" to "The canvas has changed. Adjust its size again",
        "调整画布会超出撤销内存限制" to "Resizing the canvas would exceed the undo memory limit",
        "图像已导入为图层" to "Image imported as a layer",
        "导入图层请选择 PNG、JPEG 或静态 WebP 图片" to "Choose a PNG, JPEG or static WebP image to import as a layer",
        "暂不支持动画 PNG，请先导出为静态图片" to "Animated PNG is not supported; export a still image first",
        "导入图层超过撤销内存限制" to "The imported layer exceeds the undo memory limit",
        "导入图层数据无效" to "The layer import data is invalid",
        "关于与更新" to "About & updates",
        "稳定版" to "Stable",
        "软件更新" to "Software update",
        "正在检查更新" to "Checking for updates",
        "已是最新版本" to "You're up to date",
        "发现新版本" to "Update available",
        "正在下载" to "Downloading",
        "安装包已就绪" to "Ready to install",
        "暂时无法更新" to "Update unavailable",
        "打开下载文件夹" to "Show download folder",
        "下载更新" to "Download update",
        "重新检查" to "Check again",
        "重试" to "Retry",
        "检查更新" to "Check for updates",
        "更新内容" to "What's new",
        "连接失败，请稍后重试" to "Could not connect. Please try again.",
        "更新信息无效" to "Invalid update information",
        "安装包校验失败，请重新下载" to "Verification failed. Download again.",
        "无法保存安装包，请检查磁盘空间" to "Could not save the installer. Check available disk space.",
        "更新通道尚未配置" to "Update channel is not configured",
        "工作台" to "Studio",
        "导出图像" to "Export image",
        "导出" to "Export",
        "透明背景" to "Transparent background",
        "JPEG 使用白色背景" to "JPEG uses a white background",
        "图像质量" to "Image quality",
        "高兼容" to "Compatible",
        "无损" to "Lossless",
        "JPEG 已导出" to "JPEG exported",
        "WebP 已导出" to "WebP exported",
        "ORA 已导出" to "ORA exported",
        "TIFF 已导出" to "TIFF exported",
        "BMP 已导出" to "BMP exported",
        "PSD 已导出" to "PSD exported",
        "PSD 文件超过大小限制" to "PSD file exceeds the size limit",
        "保留图层" to "Layers",
        "保留图层与透明度" to "Layers and transparency",
        "图层名称包含不支持的字符" to "Layer name contains unsupported characters",
        "缩略图生成失败" to "Could not generate thumbnails",
        "跳过启动动画" to "Skip intro",
        "画笔" to "Brush",
        "笔刷库" to "Brush library",
        "橡皮" to "Eraser",
        "矩形选区" to "Marquee",
        "选区" to "Selection",
        "剪贴板" to "Clipboard",
        "变换图层" to "Transform layer",
        "渐变" to "Gradient",
        "线性渐变" to "Linear gradient",
        "径向渐变" to "Radial gradient",
        "反转渐变" to "Reverse gradient",
        "淡出到透明" to "Fade to transparent",
        "渐变不透明度" to "Gradient opacity",
        "确认渐变" to "Apply gradient",
        "取消渐变" to "Cancel gradient",
        "渐变已完成" to "Gradient applied",
        "渐变参数无效" to "Invalid gradient parameters",
        "渐变会超出撤销内存限制" to "Gradient exceeds the undo memory limit",
        "画布已改变，请重新绘制渐变" to "The canvas changed. Draw the gradient again",
        "请先确认或取消渐变" to "Apply or cancel the gradient first",
        "水平翻转图层" to "Flip layer horizontally",
        "垂直翻转图层" to "Flip layer vertically",
        "顺时针旋转 90°" to "Rotate 90° clockwise",
        "像素采样" to "Pixel sampling",
        "重置变换" to "Reset transform",
        "取消变换" to "Cancel transform",
        "确认变换" to "Apply transform",
        "图层变换已完成" to "Layer transformed",
        "图层变换参数无效" to "Invalid layer transform",
        "当前图层没有可变换的内容" to "This layer contains no pixels to transform",
        "图层变换会超出撤销内存限制" to "Layer transform exceeds the undo memory limit",
        "图层已变化，请重新开始变换" to "The layer changed, please restart the transform",
        "请先取消选区，再变换图层" to "Clear the selection before transforming the layer",
        "请先确认或取消图层变换" to "Apply or cancel the layer transform first",
        "复制当前图层" to "Copy active layer",
        "复制可见画面" to "Copy visible",
        "剪切" to "Cut",
        "粘贴为新图层" to "Paste as new layer",
        "粘贴的图像" to "Pasted image",
        "已复制图片" to "Image copied",
        "已剪切，可撤销" to "Cut, undo available",
        "已粘贴到新图层" to "Pasted as new layer",
        "当前平台暂不支持图片剪贴板" to "Image clipboard is unavailable on this platform",
        "剪贴板中没有图片" to "The clipboard contains no image",
        "剪贴板正被占用，请稍后重试" to "Clipboard is busy, please try again",
        "剪贴板图片过大" to "Clipboard image is too large",
        "剪贴板图片尺寸超出限制" to "Clipboard image dimensions exceed the limit",
        "剪贴板图片数据无效" to "Invalid clipboard image",
        "剪贴板图片位置无效" to "Invalid clipboard image position",
        "剪贴板图片没有可见内容" to "Clipboard image contains no visible pixels",
        "剪贴板图片尚未就绪" to "Clipboard image is not ready",
        "读取剪贴板图片失败" to "Could not read the clipboard image",
        "复制图像失败" to "Could not copy the image",
        "复制选项无效" to "Invalid copy option",
        "选中区域没有可复制的内容" to "The selected area contains no pixels to copy",
        "剪切内容超过撤销内存限制" to "Cut exceeds the undo memory limit",
        "椭圆选区" to "Ellipse selection",
        "自由套索" to "Freehand lasso",
        "魔棒选区" to "Magic wand",
        "全部笔刷" to "All brushes",
        "收藏的笔刷" to "Favorites",
        "扩展笔刷" to "Extensions",
        "搜索笔刷" to "Search brushes",
        "清除搜索" to "Clear search",
        "收藏笔刷" to "Favorite brush",
        "取消收藏笔刷" to "Unfavorite brush",
        "点亮星标，收藏常用笔刷" to "Star a brush to keep it here",
        "没有匹配的笔刷" to "No matching brushes",
        "保存笔刷" to "Save brush",
        "另存笔刷副本" to "Save a copy",
        "魔棒设置" to "Magic wand options",
        "容差" to "Tolerance",
        "仅连续区域" to "Contiguous only",
        "取样所有可见图层" to "Sample visible layers",
        "取样位置超出画布" to "Sample point is outside the canvas",
        "连续区域过于复杂，请缩小图像后重试" to "Region is too complex. Reduce the image size and try again.",
        "套索路径无效或过长" to "Invalid or excessive lasso path",
        "选区超出画布或为空" to "Selection is empty or outside the canvas",
        "选区为空" to "Selection is empty",
        "选区参数无效" to "Invalid selection settings",
        "填充" to "Fill",
        "取色" to "Eyedropper",
        "移动" to "Pan",
        "移动画布" to "Pan canvas",
        "颜色" to "Color",
        "调色盘" to "Color wheel",
        "图层" to "Layers",
        "锁定透明度" to "Lock alpha",
        "解除透明度锁定" to "Unlock alpha",
        "锁定图层" to "Lock layer",
        "解锁图层" to "Unlock layer",
        "图层已锁定，请先解锁" to "Unlock this layer before editing",
        "请先解除透明度锁定" to "Unlock alpha first",
        "请先解锁要合并的图层" to "Unlock the layers before merging",
        "工程版本不受支持，请更新 podor" to "Unsupported project version. Update podor to open it.",
        "混合模式" to "Blend mode",
        "正常" to "Normal",
        "正片叠底" to "Multiply",
        "滤色" to "Screen",
        "叠加" to "Overlay",
        "柔光" to "Soft light",
        "变暗" to "Darken",
        "变亮" to "Lighten",
        "差值" to "Difference",
        "调整" to "Adjust",
        "设置" to "Settings",
        "语言" to "Language",
        "快捷键" to "Shortcuts",
        "插件" to "Plugins",
        "关闭" to "Close",
        "收起面板" to "Hide panel",
        "展开面板" to "Show panel",
        "拖动缩略图排序" to "Drag thumbnail to reorder",
        "图层已变化，请重新排序" to "The layers changed. Drag again",
        "移动图层" to "Move layer",
        "平移画布" to "Pan canvas",
        "超出画布的部分会裁切" to "Content outside the canvas is clipped",
        "取消移动" to "Cancel move",
        "准备图层…" to "Preparing layer…",
        "请先取消选区，再移动图层" to "Deselect before moving the layer",
        "图层已变化，请重新移动" to "The layer changed. Move it again",
        "移动距离超出画布尺寸" to "Move exceeds canvas dimensions",
        "图层内容过多，移动会超出撤销内存限制" to "This move would exceed the undo memory limit",
        "最小化" to "Minimize",
        "最大化" to "Maximize",
        "还原窗口" to "Restore window",
        "编辑笔刷" to "Brush editor",
        "大小" to "Size",
        "不透明度" to "Opacity",
        "墨水笔" to "Ink",
        "勾线笔" to "Liner",
        "稳笔" to "Stabilization",
        "笔尖" to "Tip",
        "压感" to "Pressure",
        "响应" to "Response",
        "轻压" to "Light pressure",
        "重压" to "Firm pressure",
        "轻柔" to "Soft",
        "线性" to "Linear",
        "有力" to "Firm",
        "压感曲线" to "Pressure curve",
        "粗细压感" to "Size pressure",
        "透明度压感" to "Opacity pressure",
        "压感墨笔" to "Pressure ink",
        "薄涂笔" to "Glaze",
        "马克笔" to "Marker",
        "柔边笔" to "Soft",
        "铅笔" to "Pencil",
        "炭笔" to "Charcoal",
        "喷枪" to "Airbrush",
        "水彩" to "Watercolor",
        "斜头笔" to "Chisel",
        "平刷" to "Flat",
        "缎带" to "Ribbon",
        "干刷" to "Dry brush",
        "排线笔" to "Hatching",
        "跟随笔画方向" to "Follow stroke direction",
        "点描" to "Stipple",
        "手指绘画" to "Finger drawing",
        "名称" to "Name",
        "圆形" to "Round",
        "扁平" to "Flat",
        "硬度" to "Hardness",
        "笔尖比例" to "Aspect",
        "角度" to "Angle",
        "颗粒" to "Grain",
        "间距" to "Spacing",
        "保存为新笔刷" to "Save as new brush",
        "完成" to "Done",
        "取消" to "Cancel",
        "按下快捷键" to "Press a shortcut",
        "恢复默认" to "Reset defaults",
        "仅支持字母、数字和组合键" to "Use a letter or digit with optional modifiers",
        "快捷键已被占用" to "Shortcut already in use",
        "导入笔刷包" to "Import brush pack",
        "导出笔刷包" to "Export brush pack",
        "导入 JSON 笔刷扩展包" to "Import a JSON brush pack",
        "移除插件" to "Remove plugin",
        "自定义笔刷" to "Custom brushes",
        "删除笔刷" to "Delete brush",
        "自由创作" to "Untitled",
        "工程菜单" to "Project",
        "新建画布" to "New canvas",
        "打开工程 / 图片" to "Open project / image",
        "保存工程" to "Save project",
        "清空当前图层" to "Clear layer",
        "快捷键与手势" to "Shortcuts & gestures",
        "取消选区" to "Deselect",
        "撤销" to "Undo",
        "重做" to "Redo",
        "导出" to "Export",
        "适合窗口" to "Fit canvas",
        "更多工具" to "More tools",
        "图层与工作台" to "Layers & studio",
        "画笔、颜色与图层" to "Studio",
        "关闭工作台" to "Close studio",
        "选择颜色" to "Color picker",
        "饱和度与明度色板" to "Saturation and brightness",
        "色相" to "Hue",
        "HEX 颜色" to "HEX color",
        "工作室色卡" to "Studio palette",
        "新建选区" to "Replace selection",
        "添加到选区" to "Add to selection",
        "从选区减去" to "Subtract from selection",
        "与选区相交" to "Intersect selection",
        "反选" to "Invert selection",
        "请先创建选区" to "Create a selection first",
        "选区为空" to "Selection is empty",
        "选区已更新" to "Selection updated",
        "我的色卡" to "My palette",
        "从画布提取颜色" to "Extract canvas colors",
        "保存当前颜色" to "Save current color",
        "移除此颜色" to "Remove this color",
        "画布上没有可提取的颜色" to "No painted colors to extract",
        "已提取画布颜色" to "Canvas colors extracted",
        "色卡空间不足，请先移除一些颜色" to "Palette is full. Remove some colors first",
        "色卡数量无效" to "Invalid palette size",
        "请先结束笔画" to "Finish the current stroke first",
        "饱和度" to "Saturation",
        "明度" to "Value",
        "亮度" to "Brightness",
        "对比度" to "Contrast",
        "新建图层" to "Add layer",
        "图层设置" to "Layer settings",
        "图层名称" to "Layer name",
        "复制图层" to "Duplicate layer",
        "合并可见图层" to "Merge visible layers",
        "合并图层" to "Merged layer",
        "至少需要两个可见图层" to "At least two visible layers are needed",
        "图层内容过多，合并会超出撤销内存限制" to "Merging these layers would exceed the undo memory limit",
        "图层不透明度" to "Layer opacity",
        "重命名" to "Rename",
        "上移图层" to "Move up",
        "下移图层" to "Move down",
        "删除图层" to "Delete layer",
        "重命名图层" to "Rename layer",
        "保存" to "Save",
        "明暗与色彩" to "Tone & color",
        "仅作用于当前图层的选区" to "Active layer selection",
        "作用于当前图层" to "Active layer",
        "应用色彩调整" to "Apply tone",
        "高斯模糊" to "Gaussian blur",
        "半径" to "Radius",
        "应用模糊" to "Apply blur",
        "填充设置" to "Fill",
        "颜色容差" to "Tolerance",
        "点击应用后生效，可随时撤销。" to "Apply, then undo at any time.",
        "选择填充工具，轻点连通区域。颜色与不透明度沿用画笔设置。" to "Tap a connected area. Uses brush color and opacity.",
        "请先保存当前工程，新画布会替换当前内容。" to "Save your work before replacing the canvas.",
        "打开工程或图片" to "Open project or image",
        "打开后会替换当前画布，重要改动请先保存。" to "Save your work before opening another canvas.",
        "选择文件" to "Choose file",
        "清空当前图层？" to "Clear this layer?",
        "清空后仍可撤销。" to "You can undo this action.",
        "清空" to "Clear",
        "暂时无法完成" to "Unable to complete",
        "知道了" to "OK",
        "宽度" to "Width",
        "高度" to "Height",
        "安装前会退出 podor，完成后重新打开，不会自动重启电脑。" to
            "podor will close for installation and open afterward. Your computer will not restart automatically.",
        "安装并打开" to "Install and open",
        "下载文件夹" to "Downloads folder",
        "无法启动安装程序，请打开下载文件夹重试" to "Could not start setup. Open the download folder to try again.",
        "当前平台不支持安装更新" to "Installing updates is not supported on this platform",
        "创建" to "Create",
        "自定义尺寸" to "Custom size",
        "尺寸超出限制" to "Size exceeds limits",
        "横向画布" to "Landscape",
        "方形画布" to "Square",
        "竖向画布" to "Portrait",
        "高清画布" to "HD",
        "交换宽高" to "Swap dimensions",
        "准备画布…" to "Preparing canvas…",
        "画布已就绪" to "Canvas ready",
        "工程已打开" to "Project opened",
        "PNG 已导出" to "PNG exported",
        "工程已保存" to "Project saved",
        "笔刷包已导入" to "Brush pack imported",
        "笔刷包过大" to "Brush pack is too large",
        "笔刷包参数无效" to "Invalid brush pack",
        "设置参数无效" to "Invalid settings",
        "插件数量超过限制" to "Plugin limit reached",
        "设置文件无法读取，已使用默认设置" to "Could not read settings; defaults loaded",
        "填充位置不在选区内" to "Fill position is outside the selection",
        "请先显示当前图层" to "Show the active layer first",
        "已达到图层上限" to "Layer limit reached",
        "至少保留一个图层" to "Keep at least one layer",
        "画布尺寸超出限制" to "Canvas size exceeds limits",
        "不是有效的podor工程" to "Not a valid podor project",
        "文件过大" to "File is too large",
        "请选择 podor、PSD、ORA 工程或 PNG、JPEG、WebP 图片" to "Choose a podor, PSD or ORA project, or a PNG, JPEG or WebP image",
        "ORA 压缩包已损坏" to "The ORA archive is damaged",
        "ORA 文件目录无效" to "The ORA file directory is invalid",
        "ORA 类型信息无效" to "The ORA media type is invalid",
        "这不是有效的 ORA 文件" to "This is not a valid ORA file",
        "ORA 图层信息无效" to "The ORA layer information is invalid",
        "ORA 图层数量超过上限" to "The ORA file exceeds the layer limit",
        "暂不支持含图层组的 ORA，请先在原软件中取消分组" to "ORA layer groups are not supported yet. Ungroup them in the original app first",
        "ORA 含有暂不支持的图层类型" to "The ORA file contains unsupported layer types",
        "ORA 图层名称过长" to "An ORA layer name is too long",
        "ORA 图层不透明度无效" to "An ORA layer opacity is invalid",
        "ORA 图层可见性无效" to "An ORA layer visibility is invalid",
        "ORA 使用了暂不支持的混合模式" to "The ORA file uses an unsupported blend mode",
        "ORA 缺少图层图像" to "An ORA layer image is missing",
        "ORA 图层路径无效" to "An ORA layer path is invalid",
        "ORA 图层必须为 PNG 图片" to "ORA layers must be PNG images",
        "ORA 图层图像无法读取" to "An ORA layer image cannot be read",
        "ORA 图层图像过大" to "An ORA layer image is too large",
        "ORA 图层图像已损坏" to "An ORA layer image is damaged",
        "ORA 文件目录过大或格式不受支持" to "The ORA directory is too large or unsupported",
        "ORA 缺少必要文件" to "The ORA file is missing required entries",
        "ORA 图层信息过大" to "The ORA layer metadata is too large",
        "ORA 文件已损坏" to "The ORA file is damaged",
        "ORA 图层属性无效" to "An ORA layer property is invalid",
        "ORA 缺少画布尺寸" to "The ORA canvas dimensions are missing",
        "ORA 图层 PNG 无法读取" to "An ORA layer PNG cannot be read",
        "ORA 图层不支持动画 PNG" to "Animated PNG layers are not supported in ORA",
        "ORA 图层 PNG 已损坏" to "An ORA layer PNG is damaged",
        "ORA 图层 PNG 颜色格式不受支持" to "An ORA layer PNG color format is unsupported",
        "PSD 文件已损坏" to "The PSD file is damaged",
        "PSD 包含尚未支持的图层属性，请先栅格化特效、文字或智能对象" to "This PSD has unsupported layer properties. Rasterize effects, text or smart objects first",
        "暂不支持 PSB，请另存为 PSD" to "PSB is not supported. Save as PSD first",
        "PSD 仅支持 RGB 和透明度通道，请移除额外通道" to "PSD supports RGB and transparency channels. Remove extra channels first",
        "PSD 目前支持 8 位 RGB，请先转换颜色模式" to "PSD currently supports 8-bit RGB. Convert the color mode first",
        "PSD 图层数量超出限制" to "The PSD has too many layers",
        "PSD 解码像素超过限制" to "PSD decoding exceeds the pixel limit",
        "PSD 蒙版尚未支持，请先应用蒙版" to "PSD masks are not supported. Apply masks first",
        "PSD 合成图含额外通道，请保存包含像素图层的 PSD" to "The merged PSD has extra channels. Save a PSD with pixel layers",
        "PSD 图层尺寸超出限制" to "A PSD layer exceeds the size limit",
        "PSD 图层组尚未支持，请先合并图层组" to "PSD groups are not supported. Merge layer groups first",
        "PSD 包含尚未支持的混合模式" to "The PSD uses an unsupported blend mode",
        "PSD 剪贴蒙版尚未支持，请先合并剪贴图层" to "PSD clipping masks are not supported. Merge clipped layers first",
        "PSD 混合颜色带尚未支持，请先栅格化该图层" to "PSD Blend If ranges are not supported. Rasterize the layer first",
        "PSD 图层名称过长" to "A PSD layer name is too long",
        "PSD 压缩方式不受支持" to "The PSD compression method is unsupported",
        "图片数据损坏或格式不受支持" to "Image is damaged or its format is unsupported",
        "暂不支持动态 WebP，请先导出为静态图片" to "Animated WebP is not supported; export a still image first",
        "图片解码超过内存限制" to "Image decoding exceeds the memory limit",
        "无法读取图片方向" to "Could not read image orientation",
        "工程文件已损坏" to "Project file is damaged",
        "导入的图像" to "Imported image",
        "对称绘画" to "Symmetry",
        "对称绘画适用于画笔和橡皮" to "Symmetry is available for brushes and erasers",
        "关闭对称" to "Symmetry off",
        "左右对称" to "Vertical symmetry",
        "上下对称" to "Horizontal symmetry",
        "双轴对称" to "Quadrant symmetry",
        "横向位置" to "Horizontal position",
        "纵向位置" to "Vertical position",
        "显示对称轴" to "Show symmetry guides",
        "对称轴居中" to "Center symmetry axes",
        "对称轴位置无效" to "Invalid symmetry axis position",
        "涂抹暂不支持对称绘画" to "Symmetry is not yet available for smudging",
    )
